stages:
  - deploy

deploy_to_heroku:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y curl
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku git:remote -a genadam
    - echo "machine api.heroku.com login _ password $HEROKU_API_KEY" > ~/.netrc
    - echo "machine git.heroku.com login _ password $HEROKU_API_KEY" >> ~/.netrc
    - chmod 600 ~/.netrc
    - git checkout main
  script:
    - git push https://git.heroku.com/genadam.git main
  only:
    - main

