stages:
  - deploy

deploy_to_heroku:
  stage: deploy
  before_script:
    # Install necessary tools
    - apt-get update && apt-get install -y curl
    - curl https://cli-assets.heroku.com/install.sh | sh
    # Set Heroku remote
    - heroku git:remote -a genadam
  script:
    # Authenticate Heroku CLI
    - heroku auth:token | git credential-cache --timeout=3600
    # Use HTTPS URL with Heroku API Key
    - git remote set-url heroku https://oauth2:$HEROKU_API_KEY@git.heroku.com/genadam.git
    # Push the code to Heroku
    - git push heroku main
  only:
    - main
  environment:
    name: production

