deploy_to_heroku:
  stage: deploy
  before_script:
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku git:remote -a genadam-2669f82f8579
  script:
    - echo "Deploying to Heroku..."
    - git push heroku main
  only:
    - main
  environment:
    name: production

