app = "genadam-analytics"
[build]
  dockerfile = "Dockerfile"
[env]
  PORT = "8086"
[http_service]
  internal_port = 8086
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
[[services]]
  protocol = "tcp"
  internal_port = 8086
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
